# Generated by Django 4.1.3 on 2022-12-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_user_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.TextField(default=None, null=True),
        ),
    ]
